export const LOGIN = 'LOGIN';
export const LOGINCOMPLETE = 'LOGINCOMPLETE';
export const LOGINERROR = 'LOGINERROR';
export const LOGOUT = 'LOGOUT';

export const GETUSERDATA = 'GETUSERDATA';
export const GETUSERDATACOMPLETE = 'GETUSERDATACOMPLETE';
